### PR TITLE
use IFileSystem to improve testability of DiskDirectoryBlobStorage

### PR DESCRIPTION
**Pull request by gerrewsb**
### Description

Improves testability of DiskDirectoryBlobStorage

### CODE REVIEW

**Comment by robinrodricks** [comment]
This is a good idea.

However, it adds a mandatory dependency into the base FluentStorage package for a less than common use case (local disk). Can you justify this or let me know why its important in the first place? 

As I see no tests have been added, so what do you mean by "testability"?

**Comment by gerrewsb** [comment]
I meant that devs that use FluentStorage can use the DiskDirectoryBlobStorage in their unit tests can inject a MockFileSystem in there so their actual filesystem isn't used for the unit tests. Otherwise they would have to mock the IBlobStorage or use the InMemory variant in their tests. Both are valid options but they still differ a bit from using the actual DiskDirectoryBlobStorage.
One could even go deeper and mock a MockFileSystem so the behaviour of a full disk or insufficient writing priviliges can be tested.

Its also a very small library to depend on. It'll hardly make FluentStorage bigger.

**Comment by robinrodricks** [comment]
I don't like this mainly because it adds another dependency, but hopefully some other users find it useful too. Merging. Thanks for your effort. If people complain about it later on, I might revert.

**Comment by robinrodricks** [comment]
Released.

- https://www.nuget.org/packages/FluentStorage/5.6.0
- https://www.nuget.org/packages/FluentStorage.Azure.Blobs/5.3.0
- https://www.nuget.org/packages/FluentStorage.AWS/5.5.0

**Pull request merged**
